apiVersion: v1
kind: Pod
metadata:
  name: sa-demo2
spec:
  terminationGracePeriodSeconds: 1
  serviceAccountName: service-reader
  containers:
  - name: app
    image: roffe/kubectl
    command: ['sh', '-c', 'sleep 9999']